name = "Inssi Pack"
author = "Ozoku"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e1931d6625122314d50f86607ea2743a89f66cc009acc945fbe5090fc65bc16"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
