name = "Inssi Pack"
author = "Ozoku"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c7786ef289472bec8aa4a427f1d0121f195cc183b7e46191801ad284d1cd9ca"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
