name = "Inssi Pack"
author = "Ozoku"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1e27690339d311bb810d05670e4e07db19a0ef61b409616daed625ae663817c"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
