name = "Inssi Pack"
author = "Ozoku"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2d6665c0b39c949ce0065d49500ce74e659635a8844f64a66e78107cda50038"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
