name = "Inssi Pack"
author = "Ozoku"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b830c42549fc13e47bb24c7c13e7b9899811a4c02a5a379ec35b238057943a20"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
