name = "Inssi Pack"
author = "Ozoku"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9072e6575f60412a55320cc5499ea94083d2b4659ace2dc9121a11eae2acbec"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
