name = "Inssi Pack"
author = "Ozoku"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bff2d6bd6cb6e07f04d3c7fec3146b3aec0dd252933371c8afafee18d7057ff"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
